const skillsByCategory = [
  {
    type: "Art and Design",
    skills: [
      "Drawing",
      "Sketching",
      "Painting",
      "Digital Art",
      "Graphic Design",
      "Creativity",
      "Photoshop",
      "Illustrator",
      "Art History",
      "Color Theory",
      "Sculpting",
      "Animation",
      "Portrait Art",
      "Typography",
      "Fine Arts",
      "Concept Art",
      "Illustration",
      "Photography",
      "Aesthetic Sense",
      "Storyboarding",
      "Visual Composition",
      "Layout Design",
      "Branding",
      "Adobe After Effects",
      "Iconography",
      "Wireframing",
      "Figma",
      "Prototyping",
      "Image Editing",
    ],
  },
  {
    type: "Engineering and Technology",
    skills: [
      "Aerodynamics",
      "Physics",
      "Mechanics",
      "CAD (Computer-Aided Design)",
      "Drone Technology",
      "MATLAB",
      "Problem-Solving",
      "Structural Analysis",
      "Fluid Dynamics",
      "3D Modeling",
      "Circuit Design",
      "Robotics",
      "Finite Element Analysis",
      "Propulsion Systems",
      "Data Analysis",
      "Engineering Software",
      "Mechanical Design",
      "Thermodynamics",
      "Avionics",
      "Control Systems",
      "Automobile Engineering",
      "CNC Programming",
      "Welding",
      "Machine Dynamics",
      "Design Engineering",
      "Vehicle Dynamics",
      "Powertrain Systems",
      "Fluid Mechanics",
      "Chassis Design",
      "Suspension Design",
      "Electrical Systems",
      "Rapid Prototyping",
      "Safety Analysis",
      "Electrical Wiring",
      "Embedded Systems",
      "Electronics",
      "Algorithm Development",
      "Microcontrollers",
      "Automation",
      "Sensors",
      "Soldering",
      "Artificial Intelligence",
      "Actuators",
    ],
  },
  {
    type: "Programming and Computer Science",
    skills: [
      "Competitive Programming",
      "Data Structures",
      "Algorithms",
      "C++",
      "Python",
      "Java",
      "JavaScript",
      "System Design",
      "Optimization",
      "Complexity Analysis",
      "Debugging",
      "Logical Reasoning",
      "Recursion",
      "Sorting Techniques",
      "Graph Theory",
      "Dynamic Programming",
      "Database Management",
      "Software Development",
      "Web Development",
      "HTML",
      "CSS",
      "React",
      "Node.js",
      "Databases",
      "Cloud Computing",
      "Mobile Development",
      "App Development",
      "UI/UX Design",
      "RESTful APIs",
      "Git/GitHub",
      "Software Testing",
      "Agile Methodologies",
      "Front-End Frameworks",
      "Back-End Frameworks",
      "Cross-Platform Development",
      "API Development",
      "Browser Development",
      "Privacy Tools",
    ],
  },
  {
    type: "Performing Arts",
    skills: [
      "Acting",
      "Public Speaking",
      "Improvisation",
      "Scriptwriting",
      "Stage Management",
      "Costume Design",
      "Direction",
      "Voice Modulation",
      "Character Development",
      "Confidence Building",
      "Prop Design",
      "Memorization",
      "Expressive Body Language",
      "Lighting Techniques",
      "Sound Design",
      "Theatre Arts",
      "Stage Presence",
      "Dance Styles (Hip-Hop, Jazz, Contemporary)",
      "Choreography",
      "Rhythm",
      "Body Coordination",
      "Public Performance",
      "Flexibility",
      "Audience Engagement",
      "Musicality",
      "Partner Dance",
      "Timing",
    ],
  },
  {
    type: "Leadership and Social Skills",
    skills: [
      "Leadership",
      "Event Management",
      "Team Collaboration",
      "Mentorship",
      "Advocacy",
      "Inclusivity",
      "Empowerment",
      "Social Work",
      "Fundraising",
      "Volunteer Coordination",
      "Emotional Intelligence",
      "Strategic Planning",
      "Presentation Skills",
      "Empathy",
      "Negotiation Skills",
      "Community Building",
      "Networking",
      "Cultural Awareness",
      "Self-Motivation",
      "Conflict Resolution",
      "Organizing",
      "Social Media Management",
      "Partnerships",
      "Documentation",
    ],
  },
  {
    type: "Business and Entrepreneurship",
    skills: [
      "Entrepreneurship",
      "Innovation",
      "Business Strategy",
      "Market Research",
      "Financial Analysis",
      "Strategic Thinking",
      "Product Development",
      "Customer Research",
      "Marketing",
      "Design Thinking",
      "Planning",
      "Analytical Skills",
      "Financial Literacy",
      "Crisis Management",
    ],
  },
  {
    type: "Writing and Communication",
    skills: [
      "Writing",
      "Editing",
      "Poetry",
      "Journalism",
      "Debate",
      "Creative Writing",
      "Critical Thinking",
      "Time Management",
      "Interviewing",
      "Blogging",
      "Research Skills",
      "Literary Analysis",
      "Proofreading",
      "Fact-Checking",
      "Listening",
    ],
  },
  {
    type: "Languages",
    skills: [
      "Language Proficiency (French, German, Spanish, Japanese, etc.)",
      "Vocabulary Building",
      "Grammar",
      "Pronunciation",
      "Listening Skills",
      "Reading Comprehension",
      "Writing Skills",
      "Translation",
      "Interpretation",
      "Accent Training",
    ],
  },
  {
    type: "Community and Environmental Awareness",
    skills: [
      "Recycling",
      "Conservation",
      "Field Research",
      "Sustainability",
      "Policy Awareness",
      "Scientific Research",
      "Educational Outreach",
      "Renewable Energy",
    ],
  },
  {
    type: "Mindfulness and Personal Growth",
    skills: [
      "Meditation",
      "Mindfulness",
      "Philosophy",
      "Counseling",
      "Stress Management",
      "Adaptability",
      "Reflection",
      "Focus",
    ],
  },
  {
    type: "Sports and Fitness",
    skills: [
      "Athleticism",
      "Discipline",
      "Strategy",
      "Physical Fitness",
      "Sports Management",
      "Coordination",
      "Endurance",
      "Time Management",
      "Decision Making",
      "Agility",
      "Motivation",
    ],
  },
  {
    type: "Creative Technology",
    skills: [
      "Photography",
      "Videography",
      "Photo Editing",
      "Adobe Lightroom",
      "Lighting Techniques",
      "Camera Operation",
      "Framing",
      "Color Grading",
    ],
  },
  {
    type: "Mathematics and Analytical Thinking",
    skills: [
      "Mathematics",
      "Statistics",
      "Logic",
      "Probability",
      "Calculus",
      "Pattern Recognition",
    ],
  },
  // Add other categories...
];

export default skillsByCategory;
