const skillsAndClubs = {
  Drawing: ["AALEKH"],
  Sketching: ["AALEKH"],
  Painting: ["AALEKH"],
  "Digital Art": ["AALEKH", "Digital Design"],
  "Graphic Design": ["AALEKH", "Digital Design", "GDSC"],
  Creativity: [
    "AALEKH",
    "Drama Club",
    "GirlScript",
    "Digital Design",
    "Spark Club",
    "Srujan",
  ],
  Photoshop: ["AALEKH", "Digital Design", "Shutterbugs"],
  Illustrator: ["AALEKH", "Digital Design"],
  "Art History": ["AALEKH"],
  "Color Theory": ["AALEKH", "Digital Design"],
  Sculpting: ["AALEKH"],
  Animation: ["AALEKH", "Digital Design", "Drama Club"],
  "Portrait Art": ["AALEKH"],
  Typography: ["AALEKH", "Digital Design"],
  "Fine Arts": ["AALEKH"],
  "Concept Art": ["AALEKH"],
  Illustration: ["AALEKH"],
  Photography: ["AALEKH", "Shutterbugs"],
  "Aesthetic Sense": ["AALEKH", "Shutterbugs"],
  Storyboarding: ["AALEKH", "Digital Design"],
  "Visual Composition": ["AALEKH", "Shutterbugs"],
  "Layout Design": ["AALEKH", "Digital Design"],
  Branding: ["AALEKH", "Digital Design"],
  "Adobe After Effects": ["AALEKH", "Digital Design"],
  Iconography: ["AALEKH", "Digital Design"],
  Wireframing: ["Digital Design", "GDSC"],
  Figma: ["Digital Design", "GDSC"],
  Prototyping: ["Digital Design", "GDSC"],
  "Image Editing": ["AALEKH", "Digital Design", "Shutterbugs"],
  Aerodynamics: ["AERO"],
  Physics: ["AERO", "Maths Club"],
  Mechanics: ["AERO", "Autosports Club"],
  "CAD (Computer-Aided Design)": ["AERO", "Autosports Club", "Robotics"],
  "Drone Technology": ["AERO", "Robotics"],
  MATLAB: ["AERO", "Maths Club", "Autosports Club"],
  "Problem-Solving": [
    "AERO",
    "CodeChef",
    "GirlScript",
    "Robotics",
    "Maths Club",
  ],
  "Structural Analysis": ["AERO"],
  "Fluid Dynamics": ["AERO", "Autosports Club"],
  "3D Modeling": ["AERO", "Autosports Club", "Digital Design"],
  "Circuit Design": ["Robotics"],
  Robotics: ["Robotics", "AERO"],
  "Finite Element Analysis": ["AERO"],
  "Propulsion Systems": ["AERO"],
  "Data Analysis": ["Maths Club", "Mozilla"],
  "Engineering Software": ["AERO", "Autosports Club"],
  "Mechanical Design": ["Autosports Club"],
  Thermodynamics: ["Autosports Club"],
  Avionics: ["AERO"],
  "Control Systems": ["AERO", "Robotics"],
  "Automobile Engineering": ["Autosports Club"],
  "CNC Programming": ["Autosports Club"],
  Welding: ["Autosports Club"],
  "Machine Dynamics": ["Autosports Club"],
  "Design Engineering": ["AERO", "Autosports Club"],
  "Vehicle Dynamics": ["Autosports Club"],
  "Powertrain Systems": ["Autosports Club"],
  "Fluid Mechanics": ["Maths Club", "AERO"],
  "Chassis Design": ["Autosports Club"],
  "Suspension Design": ["Autosports Club"],
  "Electrical Systems": ["Autosports Club"],
  "Rapid Prototyping": ["Autosports Club"],
  "Safety Analysis": ["Autosports Club"],
  "Electrical Wiring": ["Robotics"],
  "Embedded Systems": ["Robotics"],
  Electronics: ["Robotics"],
  "Algorithm Development": ["CodeChef"],
  Microcontrollers: ["Robotics"],
  Automation: ["Robotics"],
  Sensors: ["Robotics"],
  Soldering: ["Robotics"],
  "Artificial Intelligence": ["GirlScript", "Robotics"],
  Actuators: ["Robotics"],
  "Competitive Programming": ["CodeChef"],
  "Data Structures": ["CodeChef"],
  Algorithms: ["CodeChef"],
  "C++": ["CodeChef", "Robotics"],
  Python: ["CodeChef", "Mozilla", "Robotics", "GirlScript"],
  Java: ["CodeChef"],
  JavaScript: ["Mozilla", "GDSC", "GirlScript"],
  "System Design": ["Mozilla", "GDSC"],
  Optimization: ["Maths Club", "Mozilla"],
  "Complexity Analysis": ["Maths Club", "CodeChef"],
  Debugging: ["CodeChef", "Mozilla"],
  "Logical Reasoning": ["Maths Club", "CodeChef"],
  Recursion: ["CodeChef"],
  "Sorting Techniques": ["CodeChef"],
  "Graph Theory": ["Maths Club", "CodeChef"],
  "Dynamic Programming": ["CodeChef"],
  "Database Management": ["GDSC"],
  "Software Development": ["GDSC", "Mozilla", "GirlScript"],
  "Web Development": ["Mozilla", "GDSC"],
  HTML: ["Mozilla", "GDSC"],
  CSS: ["Mozilla", "GDSC"],
  React: ["GDSC"],
  "Node.js": ["GDSC"],
  Databases: ["GDSC"],
  "Cloud Computing": ["GDSC"],
  "Mobile Development": ["GDSC"],
  "App Development": ["GDSC"],
  "UI/UX Design": ["Digital Design", "GDSC"],
  "RESTful APIs": ["Mozilla", "GDSC"],
  "Git/GitHub": ["Mozilla", "GDSC"],
  "Software Testing": ["GDSC"],
  "Agile Methodologies": ["Mozilla", "GDSC"],
  "Front-End Frameworks": ["GDSC"],
  "Back-End Frameworks": ["GDSC"],
  "Cross-Platform Development": ["GDSC"],
  "API Development": ["Mozilla", "GDSC"],
  "Browser Development": ["Mozilla"],
  "Privacy Tools": ["Mozilla"],
  Acting: ["Literary Club"],
  "Public Speaking": ["Literary Club", "Literary Club"],
  Improvisation: ["Literary Club"],
  Scriptwriting: ["Literary Club"],
  "Stage Management": ["Literary Club"],
  "Costume Design": ["Literary Club"],
  Direction: ["Literary Club"],
  "Voice Modulation": ["Literary Club"],
  "Character Development": ["Literary Club"],
  "Confidence Building": ["Toastmasters", "Literary Club"],
  "Prop Design": ["Literary Club"],
  Memorization: ["Literary Club"],
  "Expressive Body Language": ["Literary Club"],
  "Lighting Techniques": ["Literary Club"],
  "Sound Design": ["Literary Club"],
  "Theatre Arts": ["Literary Club"],
  "Stage Presence": ["Literary Club"],
  "Dance Styles (Hip-Hop, Jazz, Contemporary)": ["Literary Club"],
  Choreography: ["Literary Club"],
  Rhythm: ["Literary Club"],
  "Body Coordination": ["Literary Club"],
  "Public Performance": ["Literary Club"],
  Flexibility: ["Literary Club"],
  "Audience Engagement": ["Literary Club"],
  Musicality: ["Literary Club"],
  "Partner Dance": ["Literary Club"],
  Timing: ["Literary Club"],
  Leadership: ["Prakruti"],
  "Event Management": ["Literary Club", "Prakruti"],
  "Team Collaboration": ["Prakruti", "Sports Club"],
  Mentorship: ["Prakruti"],
  Advocacy: ["Prakruti"],
  Inclusivity: ["Prakruti"],
  Empowerment: ["Prakruti"],
  "Social Work": ["Robotics"],
  Fundraising: ["Robotics"],
  "Volunteer Coordination": ["Robotics"],
  "Emotional Intelligence": ["Prakruti"],
  "Strategic Planning": ["Prakruti"],
  "Presentation Skills": ["Literary Club", "Prakruti"],
  Empathy: ["Robotics"],
  "Negotiation Skills": ["Prakruti"],
  "Community Building": ["Robotics"],
  Networking: ["Prakruti"],
  "Cultural Awareness": ["Literary Club"],
  "Self-Motivation": ["Prakruti"],
  "Conflict Resolution": ["Prakruti"],
  Organizing: ["Prakruti"],
  Partnerships: ["Prakruti"],
  Entrepreneurship: ["GOONJ"],
  Innovation: ["GOONJ"],
  "Business Strategy": ["GOONJ"],
  "Market Research": ["GOONJ"],
  "Financial Analysis": ["GOONJ"],
  "Strategic Thinking": ["GOONJ"],
  "Product Development": ["GOONJ"],
  "Customer Research": ["GOONJ"],
  Marketing: ["GOONJ"],
  "Design Thinking": ["GOONJ", "Digital Design"],
  Planning: ["GOONJ"],
  "Analytical Skills": ["GOONJ"],
  "Financial Literacy": ["GOONJ"],
  "Crisis Management": ["GOONJ"],
  Writing: ["Literary Club"],
  Editing: ["Literary Club"],
  Poetry: ["Literary Club"],
  Debate: ["Toastmasters", "Literary Club"],
  "Creative Writing": ["Literary Club"],
  "Critical Thinking": ["Toastmasters", "Literary Club"],
  "Time Management": ["Prakruti", "Sports Club"],
  "Research Skills": ["Literary Club"],
  "Literary Analysis": ["Literary Club"],

  Listening: ["Literary Club"],
  "Language Proficiency (French, German, Spanish, Japanese, etc.)": [
    "F. L. Club",
  ],
  "Vocabulary Building": ["F. L. Club"],
  Grammar: ["F. L. Club"],
  Pronunciation: ["F. L. Club"],
  "Listening Skills": ["F. L. Club"],
  "Reading Comprehension": ["F. L. Club"],
  "Writing Skills": ["F. L. Club"],
  Translation: ["F. L. Club"],
  Interpretation: ["F. L. Club"],
  "Accent Training": ["F. L. Club"],
  Recycling: ["Literary Club"],
  Conservation: ["Literary Club"],
  "Field Research": ["Literary Club"],
  Sustainability: ["Literary Club"],
  "Policy Awareness": ["Literary Club"],
  "Scientific Research": ["Literary Club"],
  "Educational Outreach": ["Literary Club", "Robotics"],
  "Renewable Energy": ["Literary Club"],
  Meditation: ["Ignited Minds"],
  Mindfulness: ["Ignited Minds"],
  Philosophy: ["Ignited Minds"],
  Counseling: ["Ignited Minds"],
  "Stress Management": ["Ignited Minds"],
  Adaptability: ["Ignited Minds"],
  Reflection: ["Ignited Minds"],
  Focus: ["Ignited Minds"],
  Athleticism: ["Sports Club"],
  Discipline: ["Sports Club"],
  Strategy: ["Sports Club"],
  "Physical Fitness": ["Sports Club"],
  "Sports Management": ["Sports Club"],
  Coordination: ["Sports Club"],
  Endurance: ["Sports Club"],
  "Decision Making": ["Sports Club"],
  Agility: ["Sports Club"],
  Motivation: ["Sports Club"],

  Mathematics: ["Maths Club"],
  Statistics: ["Maths Club"],
  Logic: ["Maths Club"],
  Probability: ["Maths Club"],
  Calculus: ["Maths Club"],
  "Pattern Recognition": ["Maths Club"],
};

export default skillsAndClubs;
